In [ ]:
import numpy as np

arr = np.array([[1,34,5,5],[3,4,5,6]])
# swap the first row with first line is not 0



- Try swapping

In [9]:
import numpy as np
arr = np.array([[1,34,5,5],[3,4,5,6]])

arr[0], arr[1] = arr[1], arr[0]

print(arr)

print(arr.shape[0],arr.shape[1])


[[3 4 5 6]
 [3 4 5 6]]
2 4


-  *.any()* in list help to check if the element in list
- shape return list of course u can apply any attribute of list 

In [12]:

import numpy as np
# Function to check if matrix is in REF

def is_row_echelon_form(matrix):
    if not matrix.any():
        return False

    rows = matrix.shape[0]
    cols = matrix.shape[1]
    prev_leading_col = -1

    for row in range(rows):
        leading_col_found = False
        for col in range(cols):
            if matrix[row, col] != 0:
                if col <= prev_leading_col:
                    return False
                prev_leading_col = col
                leading_col_found = True
                break
        if not leading_col_found and any(matrix[row, col] != 0 for col in range(cols)):
            return False
    return True

def find_nonzero_row(matrix, pivot_row, col):
    nrows = matrix.shape[0]
    for row in range(pivot_row, nrows):
        if matrix[row, col] != 0:
            return row
    return None

# Swapping rows so that we can have our non zero row on the top of the matrix
def swap_rows(matrix, row1, row2):
    matrix[[row1, row2]] = matrix[[row2, row1]]

def make_pivot_one(matrix, pivot_row, col):
    pivot_element = matrix[pivot_row, col]
    matrix[pivot_row] //= pivot_element
    # print(pivot_element)

def eliminate_below(matrix, pivot_row, col):
    nrows = matrix.shape[0]
    pivot_element = matrix[pivot_row, col]
    for row in range(pivot_row + 1, nrows):
        factor = matrix[row, col]
        matrix[row] -= factor * matrix[pivot_row]

# Implementing above functions
def row_echelon_form(matrix):
    nrows = matrix.shape[0]
    ncols = matrix.shape[1]
    pivot_row = 0
# this will run for number of column times. If matrix has 3 columns this loop will run for 3 times
    for col in range(ncols):
        nonzero_row = find_nonzero_row(matrix, pivot_row, col)
        if nonzero_row is not None:
            swap_rows(matrix, pivot_row, nonzero_row)
            make_pivot_one(matrix, pivot_row, col)
            eliminate_below(matrix, pivot_row, col)
            pivot_row += 1
    return matrix


matrix = np.array([[2,-2,4,-2],[2,1,10,7],[-4,4,-8,4],[4,-1,14,6]])
print("Matrix Before Converting:")
print(matrix)
print()
result = row_echelon_form(matrix)
print("After Converting to Row Echelon Form:")
print(result)
if is_row_echelon_form(result):
    print("In REF")
else:
    print("Not in REF--------------->")

Matrix Before Converting:
[[ 2 -2  4 -2]
 [ 2  1 10  7]
 [-4  4 -8  4]
 [ 4 -1 14  6]]

After Converting to Row Echelon Form:
[[ 1 -1  2 -1]
 [ 0  1  2  3]
 [ 0  0  0  1]
 [ 0  0  0  0]]
In REF


In [32]:
import numpy as np

def swapping(matrix,row1,row2):
    matrix[[row1,row2]] = matrix[[row2,row1]]

def non_zeros(matrix,pivot_row,col):
    nrows = matrix.shape[0]
    for row in range(pivot_row,nrows):
        if abs(matrix[row,col]) > 1e-6:
            return row
    return None

def make_pivot(matrix,pivot,col):
    pivot_element = matrix[pivot,col]
    matrix[pivot] /= pivot_element
# pivot row is divided into 1 -> easy to calculate

def eliminate_below(matrix,pivot_row,col):
    nrow = matrix.shape[0]
    for row in range(pivot_row+1,nrow):
        factor = matrix[row,col]
        matrix[row] -= factor*matrix[pivot_row]

def form_Echelon(matrix):
    nrow = matrix.shape[0]
    ncol = matrix.shape[1]

    pivot = 0

    for col in range(ncol):
        non = non_zeros(matrix=matrix,pivot_row=pivot,col=col)
        if non is not None:
            swapping(matrix=matrix,row1=pivot,row2=non)
            make_pivot(matrix,pivot=pivot,col=col)
            eliminate_below(matrix=matrix,pivot_row=pivot,col=col)
            pivot += 1
    
    return matrix


matrix = np.array([[3,-2,4,-2],[2,1,10,7],[-4,4,-8,4],[4,-1,14,6]],dtype=float)





result = form_Echelon(matrix=matrix)
print(result)

[[ 1.         -0.66666667  1.33333333 -0.66666667]
 [ 0.          1.          3.14285714  3.57142857]
 [-0.         -0.          1.          0.5       ]
 [ 0.          0.          0.          1.        ]]
